### ISSUE TITLE
unable to dump config when using tfe with keras model

### ISSUE THREAD

**Issue by theRealSuperMario** [pesser/edflow#240]
When adding the config to a model that inherits from `tf.keras.Model`, the config cannot be dumped.
It looks like keras changes lists within the config to a `ListWrapper` object, which are not reduceably by `yaml.dump`

**To Reproduce**

```python
"""exp.py"""
import tensorflow as tf

tf.enable_eager_execution()

from tensorflow import keras as tfk
import numpy as np
from edflow import TemplateIterator, get_logger


class Model(tfk.Model):
    def __init__(self, config):
        super().__init__()
        self.config = config

    def call(self, x1, x2):
        pass

class Iterator(TemplateIterator):
    def __init__(self, *args, **kwargs):
        super(Iterator, self).__init__(*args, **kwargs)
```

```yaml
dataset: edflow.datasets.fashionmnist.FashionMNIST
validation_dataset: edflow.datasets.fashionmnist.FashionMNIST
model: exp.Model
iterator: exp.Iterator


batch_size: 4
size: 128

num_epochs: 10

foo:
  bar: [1, 2]
```

run `edflow -b config.yaml -t -n foo -d` gives 

> NotImplementedError: object proxy must define __reduce_ex__()

**Expected behavior**
I expect the config to be dumped

**Additional context**
Workaround is to simply not do `self.config = config` and save everything you need in a field in the model.
